algoritmo "Media"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
var
   numero1: Inteiro
   Numero2: Inteiro
   media: Real
inicio
      Escreva("Digite o primeiro numero: ")
      Leia(numero1)
      Escreva("Digite o segundo numero: ")
      Leia(numero2)
      media <- (numero1 + numero2) / 2
      Escreva("A média entre ", numero1, " e ", numero2, " é igual a", media)
fimalgoritmo