Algoritmo "OperadoresLogicos"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01.04.2024
Var
// Seção de Declarações das variáveis 
   a, b, c: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   a <- 2
   b <- 3
   c <- 5
   
   Escreva(nao((a=b) ou (c>=a)))

Fimalgoritmo